version: '3.8'

services:
  # The simulator broadcasting on 224.5.23.2:10020
  simulator:
    image:  roboticserlangen/simulatorcli
    network_mode: host
    environment:
      - GEOMETRY=2020B
      - REALISM=RC2021
    stdin_open: true
    tty: true
    restart: on-failure

  # The visualizer listening on port 10006
  gui:
    image: tigersmannheim/auto-referee-vnc
    network_mode: host
    command: [ "--visionAddress", "224.5.23.2:10020" ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=unix${DISPLAY}
    restart: on-failure
